version: "3"
services:
  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    container_name: forum-keszites-info
    environment:
      - MYSQL_DATABASE=forum-db
      - MYSQL_USER=forum-db-user
      - MYSQL_PASSWORD=adatbazis0000
      - MYSQL_HOST=adatbazis
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - adatbazis
  adatbazis:
    image: mariadb
    container_name: mysql-adatbazis
    environment:
      - MYSQL_ROOT_PASSWORD=adatbazisroot
      - MYSQL_USER=forum-db-user
      - MYSQL_PASSWORD=adatbazis0000
      - MYSQL_DATABASE=forum-db
    ports:
      - "6603:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  mysql_data: { driver: local}
